name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest # or macos-latest/windows-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 16.8 # see https://github.com/actions/setup-node#supported-version-syntax for supported versions
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Checkout branch
        uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Clean install dependencies
        run: npm ci # or yarn install --frozen-lockfile for yarn
        # if the above doesn't work, use npm i or yarn
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Build app
        run: npm run build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_DEPLOY }}
          publish_dir: ./public
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
